export const AU_SUBURBS = [
    // Major Cities (Always at top)
    { s: "Sydney", st: "NSW" }, { s: "Melbourne", st: "VIC" }, { s: "Brisbane", st: "QLD" },
    { s: "Perth", st: "WA" }, { s: "Adelaide", st: "SA" }, { s: "Gold Coast", st: "QLD" },
    { s: "Canberra", st: "ACT" }, { s: "Hobart", st: "TAS" }, { s: "Darwin", st: "NT" },

    // NSW - Comprehensive (Focus on Sydney & Surrounds)
    { s: "Abbotsbury", st: "NSW" }, { s: "Abbotsford", st: "NSW" }, { s: "Acacia Gardens", st: "NSW" },
    { s: "Alexandria", st: "NSW" }, { s: "Alfords Point", st: "NSW" }, { s: "Allambie Heights", st: "NSW" },
    { s: "Allawah", st: "NSW" }, { s: "Annandale", st: "NSW" }, { s: "Annangrove", st: "NSW" },
    { s: "Arncliffe", st: "NSW" }, { s: "Arndell Park", st: "NSW" }, { s: "Artarmon", st: "NSW" },
    { s: "Ashfield", st: "NSW" }, { s: "Asquith", st: "NSW" }, { s: "Auburn", st: "NSW" },
    { s: "Avalon Beach", st: "NSW" }, { s: "Balgowlah", st: "NSW" }, { s: "Balmain", st: "NSW" },
    { s: "Bankstown", st: "NSW" }, { s: "Barangaroo", st: "NSW" }, { s: "Bardia", st: "NSW" },
    { s: "Bass Hill", st: "NSW" }, { s: "Baulkham Hills", st: "NSW" }, { s: "Beacon Hill", st: "NSW" },
    { s: "Beaconsfield", st: "NSW" }, { s: "Beaumont Hills", st: "NSW" }, { s: "Beecroft", st: "NSW" },
    { s: "Belfield", st: "NSW" }, { s: "Bella Vista", st: "NSW" }, { s: "Bellevue Hill", st: "NSW" },
    { s: "Belmore", st: "NSW" }, { s: "Belrose", st: "NSW" }, { s: "Berala", st: "NSW" },
    { s: "Bexley", st: "NSW" }, { s: "Bexley North", st: "NSW" }, { s: "Bidwill", st: "NSW" },
    { s: "Birchgrove", st: "NSW" }, { s: "Birrong", st: "NSW" }, { s: "Blacktown", st: "NSW" },
    { s: "Bligh Park", st: "NSW" }, { s: "Bondi", st: "NSW" }, { s: "Bondi Beach", st: "NSW" },
    { s: "Bondi Junction", st: "NSW" }, { s: "Bonnet Bay", st: "NSW" }, { s: "Bonnyrigg", st: "NSW" },
    { s: "Bossley Park", st: "NSW" }, { s: "Botany", st: "NSW" }, { s: "Bowral", st: "NSW" },
    { s: "Box Hill", st: "NSW" }, { s: "Breakfast Point", st: "NSW" }, { s: "Brighton-Le-Sands", st: "NSW" },
    { s: "Bronte", st: "NSW" }, { s: "Brookvale", st: "NSW" }, { s: "Bungarribee", st: "NSW" },
    { s: "Burwood", st: "NSW" }, { s: "Busby", st: "NSW" }, { s: "Cabramatta", st: "NSW" },
    { s: "Cambridge Park", st: "NSW" }, { s: "Camden", st: "NSW" }, { s: "Cammeray", st: "NSW" },
    { s: "Campbelltown", st: "NSW" }, { s: "Camperdown", st: "NSW" }, { s: "Campsie", st: "NSW" },
    { s: "Canley Vale", st: "NSW" }, { s: "Canterbury", st: "NSW" }, { s: "Caringbah", st: "NSW" },
    { s: "Carlingford", st: "NSW" }, { s: "Carlton", st: "NSW" }, { s: "Carnes Hill", st: "NSW" },
    { s: "Carramar", st: "NSW" }, { s: "Castle Hill", st: "NSW" }, { s: "Castle Cove", st: "NSW" },
    { s: "Casula", st: "NSW" }, { s: "Catherine Field", st: "NSW" }, { s: "Chatswood", st: "NSW" },
    { s: "Cherrybrook", st: "NSW" }, { s: "Chester Hill", st: "NSW" }, { s: "Chifley", st: "NSW" },
    { s: "Chipping Norton", st: "NSW" }, { s: "Chiswick", st: "NSW" }, { s: "Chullora", st: "NSW" },
    { s: "Clyde", st: "NSW" }, { s: "Colyton", st: "NSW" }, { s: "Concord", st: "NSW" },
    { s: "Condell Park", st: "NSW" }, { s: "Coogee", st: "NSW" }, { s: "Cremorne", st: "NSW" },
    { s: "Cronulla", st: "NSW" }, { s: "Crows Nest", st: "NSW" }, { s: "Darling Point", st: "NSW" },
    { s: "Darlinghurst", st: "NSW" }, { s: "Darlington", st: "NSW" }, { s: "Davidson", st: "NSW" },
    { s: "Dawes Point", st: "NSW" }, { s: "Dean Park", st: "NSW" }, { s: "Dee Why", st: "NSW" },
    { s: "Denistone", st: "NSW" }, { s: "Doonside", st: "NSW" }, { s: "Double Bay", st: "NSW" },
    { s: "Drummoyne", st: "NSW" }, { s: "Dulwich Hill", st: "NSW" }, { s: "Dundas", st: "NSW" },
    { s: "Dural", st: "NSW" }, { s: "Earlwood", st: "NSW" }, { s: "Eastgardens", st: "NSW" },
    { s: "Eastlakes", st: "NSW" }, { s: "Eastwood", st: "NSW" }, { s: "Edgecliff", st: "NSW" },
    { s: "Elizabeth Bay", st: "NSW" }, { s: "Enmore", st: "NSW" }, { s: "Epping", st: "NSW" },
    { s: "Ermington", st: "NSW" }, { s: "Erskineville", st: "NSW" }, { s: "Fairfield", st: "NSW" },
    { s: "Five Dock", st: "NSW" }, { s: "Forest Lodge", st: "NSW" }, { s: "Forestville", st: "NSW" },
    { s: "Frenchs Forest", st: "NSW" }, { s: "Galston", st: "NSW" }, { s: "Georges Hall", st: "NSW" },
    { s: "Girraween", st: "NSW" }, { s: "Glebe", st: "NSW" }, { s: "Glenhaven", st: "NSW" },
    { s: "Glenmore Park", st: "NSW" }, { s: "Gordon", st: "NSW" }, { s: "Granville", st: "NSW" },
    { s: "Greenacre", st: "NSW" }, { s: "Greenwich", st: "NSW" }, { s: "Guildford", st: "NSW" },
    { s: "Gymea", st: "NSW" }, { s: "Haberfield", st: "NSW" }, { s: "Hammondville", st: "NSW" },
    { s: "Harris Park", st: "NSW" }, { s: "Haymarket", st: "NSW" }, { s: "Heckenberg", st: "NSW" },
    { s: "Homebush", st: "NSW" }, { s: "Hornsby", st: "NSW" }, { s: "Horsley Park", st: "NSW" },
    { s: "Hurstville", st: "NSW" }, { s: "Ingleburn", st: "NSW" }, { s: "Jamisontown", st: "NSW" },
    { s: "Jannali", st: "NSW" }, { s: "Kangaroo Point", st: "NSW" }, { s: "Kareela", st: "NSW" },
    { s: "Kellyville", st: "NSW" }, { s: "Kensington", st: "NSW" }, { s: "Killarney Heights", st: "NSW" },
    { s: "Kings Langley", st: "NSW" }, { s: "Kings Park", st: "NSW" }, { s: "Kingsford", st: "NSW" },
    { s: "Kingsgrove", st: "NSW" }, { s: "Kirrawee", st: "NSW" }, { s: "Kirribilli", st: "NSW" },
    { s: "Kogarah", st: "NSW" }, { s: "Ku-ring-gai", st: "NSW" }, { s: "Kurnell", st: "NSW" },
    { s: "Lakemba", st: "NSW" }, { s: "Lalor Park", st: "NSW" }, { s: "Lane Cove", st: "NSW" },
    { s: "Lansvale", st: "NSW" }, { s: "Lavender Bay", st: "NSW" }, { s: "Leichhardt", st: "NSW" },
    { s: "Lidcombe", st: "NSW" }, { s: "Lilli Pilli", st: "NSW" }, { s: "Lilyfield", st: "NSW" },
    { s: "Lindfield", st: "NSW" }, { s: "Linley Point", st: "NSW" }, { s: "Liverpool", st: "NSW" },
    { s: "Loftus", st: "NSW" }, { s: "Longueville", st: "NSW" }, { s: "Lucas Heights", st: "NSW" },
    { s: "Lugarno", st: "NSW" }, { s: "Lurnea", st: "NSW" }, { s: "Macquarie Park", st: "NSW" },
    { s: "Maianbar", st: "NSW" }, { s: "Malabar", st: "NSW" }, { s: "Manly", st: "NSW" },
    { s: "Maroubra", st: "NSW" }, { s: "Marrickville", st: "NSW" }, { s: "Marsfield", st: "NSW" },
    { s: "Mascot", st: "NSW" }, { s: "Matraville", st: "NSW" }, { s: "Mayfield", st: "NSW" },
    { s: "Menai", st: "NSW" }, { s: "Merrylands", st: "NSW" }, { s: "Middle Cove", st: "NSW" },
    { s: "Miller", st: "NSW" }, { s: "Millers Point", st: "NSW" }, { s: "Milperra", st: "NSW" },
    { s: "Milsons Point", st: "NSW" }, { s: "Miranda", st: "NSW" }, { s: "Monash Park", st: "NSW" },
    { s: "Moore Park", st: "NSW" }, { s: "Moorebank", st: "NSW" }, { s: "Mortdale", st: "NSW" },
    { s: "Mortlake", st: "NSW" }, { s: "Mosman", st: "NSW" }, { s: "Mount Annan", st: "NSW" },
    { s: "Mount Druitt", st: "NSW" }, { s: "Mount Lewis", st: "NSW" }, { s: "Mount Pritchard", st: "NSW" },
    { s: "Narellan", st: "NSW" }, { s: "Naremburn", st: "NSW" }, { s: "Narrabeen", st: "NSW" },
    { s: "Narwee", st: "NSW" }, { s: "Neutral Bay", st: "NSW" }, { s: "Newtown", st: "NSW" },
    { s: "Normanhurst", st: "NSW" }, { s: "North Bondi", st: "NSW" }, { s: "North Epping", st: "NSW" },
    { s: "North Ryde", st: "NSW" }, { s: "North Strathfield", st: "NSW" }, { s: "North Sydney", st: "NSW" },
    { s: "North Turramurra", st: "NSW" }, { s: "North Willoughby", st: "NSW" }, { s: "Northmead", st: "NSW" },
    { s: "Northwood", st: "NSW" }, { s: "Oakhurst", st: "NSW" }, { s: "Oakvile", st: "NSW" },
    { s: "Oatlands", st: "NSW" }, { s: "Oatley", st: "NSW" }, { s: "Old Guildford", st: "NSW" },
    { s: "Old Toongabbie", st: "NSW" }, { s: "Oran Park", st: "NSW" }, { s: "Paddington", st: "NSW" },
    { s: "Padstow", st: "NSW" }, { s: "Palm Beach", st: "NSW" }, { s: "Panania", st: "NSW" },
    { s: "Parklea", st: "NSW" }, { s: "Parramatta", st: "NSW" }, { s: "Peakhurst", st: "NSW" },
    { s: "Pemulwuy", st: "NSW" }, { s: "Pendle Hill", st: "NSW" }, { s: "Pennant Hills", st: "NSW" },
    { s: "Penrith", st: "NSW" }, { s: "Penshurst", st: "NSW" }, { s: "Petersham", st: "NSW" },
    { s: "Phillip Bay", st: "NSW" }, { s: "Point Piper", st: "NSW" }, { s: "Potts Hill", st: "NSW" },
    { s: "Potts Point", st: "NSW" }, { s: "Prairiewood", st: "NSW" }, { s: "Prestons", st: "NSW" },
    { s: "Punchbowl", st: "NSW" }, { s: "Putney", st: "NSW" }, { s: "Pymble", st: "NSW" },
    { s: "Pyrmont", st: "NSW" }, { s: "Quakers Hill", st: "NSW" }, { s: "Queens Park", st: "NSW" },
    { s: "Queenscliff", st: "NSW" }, { s: "Ramsgate", st: "NSW" }, { s: "Randwick", st: "NSW" },
    { s: "Redfern", st: "NSW" }, { s: "Regents Park", st: "NSW" }, { s: "Revesby", st: "NSW" },
    { s: "Rhodes", st: "NSW" }, { s: "Richmond", st: "NSW" }, { s: "Riverstone", st: "NSW" },
    { s: "Riverview", st: "NSW" }, { s: "Rockdale", st: "NSW" }, { s: "Rodd Point", st: "NSW" },
    { s: "Ropes Crossing", st: "NSW" }, { s: "Rose Bay", st: "NSW" }, { s: "Rosebery", st: "NSW" },
    { s: "Rosehill", st: "NSW" }, { s: "Roselands", st: "NSW" }, { s: "Roseville", st: "NSW" },
    { s: "Rouse Hill", st: "NSW" }, { s: "Rozelle", st: "NSW" }, { s: "Ruse", st: "NSW" },
    { s: "Rushcutters Bay", st: "NSW" }, { s: "Russell Lea", st: "NSW" }, { s: "Rydalmere", st: "NSW" },
    { s: "Ryde", st: "NSW" }, { s: "Sans Souci", st: "NSW" }, { s: "Schofields", st: "NSW" },
    { s: "Seaforth", st: "NSW" }, { s: "Sefton", st: "NSW" }, { s: "Seven Hills", st: "NSW" },
    { s: "Shalvey", st: "NSW" }, { s: "Silverwater", st: "NSW" }, { s: "Smithfield", st: "NSW" },
    { s: "South Hurstville", st: "NSW" }, { s: "South Penrith", st: "NSW" }, { s: "South Wentworthville", st: "NSW" },
    { s: "St Albans", st: "NSW" }, { s: "St Andrews", st: "NSW" }, { s: "St Clair", st: "NSW" },
    { s: "St Helens Park", st: "NSW" }, { s: "St Ives", st: "NSW" }, { s: "St Johns Park", st: "NSW" },
    { s: "St Leonards", st: "NSW" }, { s: "St Marys", st: "NSW" }, { s: "St Peters", st: "NSW" },
    { s: "Stanhope Gardens", st: "NSW" }, { s: "Stanmore", st: "NSW" }, { s: "Strathfield", st: "NSW" },
    { s: "Summer Hill", st: "NSW" }, { s: "Surry Hills", st: "NSW" }, { s: "Sutherland", st: "NSW" },
    { s: "Sydenham", st: "NSW" }, { s: "Sylvania", st: "NSW" }, { s: "Tamarama", st: "NSW" },
    { s: "Telopea", st: "NSW" }, { s: "Tempe", st: "NSW" }, { s: "Tenambit", st: "NSW" },
    { s: "Terrey Hills", st: "NSW" }, { s: "The Ponds", st: "NSW" }, { s: "The Rocks", st: "NSW" },
    { s: "Thornleigh", st: "NSW" }, { s: "Toongabbie", st: "NSW" }, { s: "Tregear", st: "NSW" },
    { s: "Turramurra", st: "NSW" }, { s: "Ultimo", st: "NSW" }, { s: "Undercliffe", st: "NSW" },
    { s: "Vaucluse", st: "NSW" }, { s: "Villawood", st: "NSW" }, { s: "Wahroonga", st: "NSW" },
    { s: "Waitara", st: "NSW" }, { s: "Wakeley", st: "NSW" }, { s: "Wallacia", st: "NSW" },
    { s: "Wareemba", st: "NSW" }, { s: "Warrawee", st: "NSW" }, { s: "Warriewood", st: "NSW" },
    { s: "Warwick Farm", st: "NSW" }, { s: "Waterfall", st: "NSW" }, { s: "Waterloo", st: "NSW" },
    { s: "Watsons Bay", st: "NSW" }, { s: "Wattle Grove", st: "NSW" }, { s: "Waverley", st: "NSW" },
    { s: "Waverton", st: "NSW" }, { s: "Wentworth Point", st: "NSW" }, { s: "Wentworthville", st: "NSW" },
    { s: "Werrington", st: "NSW" }, { s: "West Hoxton", st: "NSW" }, { s: "West Pennant Hills", st: "NSW" },
    { s: "West Ryde", st: "NSW" }, { s: "Westmead", st: "NSW" }, { s: "Wetherill Park", st: "NSW" },
    { s: "Whalan", st: "NSW" }, { s: "Wilberforce", st: "NSW" }, { s: "Willoughby", st: "NSW" },
    { s: "Winston Hills", st: "NSW" }, { s: "Wolli Creek", st: "NSW" }, { s: "Wollstonecraft", st: "NSW" },
    { s: "Woodpark", st: "NSW" }, { s: "Woollahra", st: "NSW" }, { s: "Woolloomooloo", st: "NSW" },
    { s: "Woolooware", st: "NSW" }, { s: "Woolwich", st: "NSW" }, { s: "Woronora", st: "NSW" },
    { s: "Yagoona", st: "NSW" }, { s: "Yarrawarrah", st: "NSW" }, { s: "Yennora", st: "NSW" },
    { s: "Zetland", st: "NSW" },
    
    // Victoria (Top Suburbs)
    { s: "South Yarra", st: "VIC" }, { s: "St Kilda", st: "VIC" }, { s: "Brunswick", st: "VIC" },
    { s: "Fitzroy", st: "VIC" }, { s: "Carlton", st: "VIC" }, { s: "Richmond", st: "VIC" },
    { s: "Prahran", st: "VIC" }, { s: "Hawthorn", st: "VIC" }, { s: "Camberwell", st: "VIC" },
    { s: "Box Hill", st: "VIC" }, { s: "Dandenong", st: "VIC" }, { s: "Frankston", st: "VIC" },
    { s: "Werribee", st: "VIC" }, { s: "Sunshine", st: "VIC" }, { s: "Footscray", st: "VIC" },
    
    // Queensland (Top Suburbs)
    { s: "South Brisbane", st: "QLD" }, { s: "Fortitude Valley", st: "QLD" }, { s: "New Farm", st: "QLD" },
    { s: "West End", st: "QLD" }, { s: "Paddington", st: "QLD" }, { s: "Indooroopilly", st: "QLD" },
    { s: "Chermside", st: "QLD" }, { s: "Mount Gravatt", st: "QLD" }, { s: "Sunnybank", st: "QLD" },
    { s: "Surfers Paradise", st: "QLD" }, { s: "Broadbeach", st: "QLD" }, { s: "Burleigh Heads", st: "QLD" }
];
