import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface InvoiceData {
  bookingId: string;
  customerName: string;
  tenantName: string;
  tenantAddress: string;
  tenantPhone: string;
  tenantABN: string;
  date: string;
  time: string;
  services: { name: string; price: number }[];
  totalPrice: number;
}

export async function generateTaxInvoice(data: InvoiceData): Promise<Blob> {
  const abn = data.tenantABN || "00 000 000 000";
  const priorityFee = 0.50; 
  const totalAmount = data.totalPrice + priorityFee;

  // IMPORTANT: Create doc and call autoTable as a standalone function for serverless stability
  const doc = new jsPDF();

  // ─── BRANDING ───
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); 
  doc.setFont("helvetica", "bold");
  doc.text("TrimSpace", 20, 25);
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("PREMIUM MARKETPLACE", 20, 30);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(data.tenantName, 190, 25, { align: "right" });
  
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(data.tenantAddress || "Location Pending", 190, 31, { align: "right" });

  // ─── TITLE ───
  doc.setDrawColor(230);
  doc.line(20, 45, 190, 45);
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text("TAX INVOICE", 20, 65);

  // ─── INFO ───
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(`Invoice #: ${data.bookingId}`, 20, 80);
  doc.text(`Issued: ${new Date().toLocaleDateString("en-AU")}`, 20, 85);
  doc.text(`Visit: ${data.date} at ${data.time}`, 20, 90);

  doc.setFont("helvetica", "bold");
  doc.text("BILL TO:", 130, 80);
  doc.setFont("helvetica", "normal");
  doc.text(data.customerName, 130, 85);

  // ─── TABLE ───
  const tableRows = data.services.map(s => [s.name, `$${s.price.toFixed(2)}`]);
  tableRows.push(["Priority Booking Fee", `$${priorityFee.toFixed(2)}`]);
  
  autoTable(doc, {
    startY: 105,
    head: [["DESCRIPTION", "AMOUNT (AUD)"]],
    body: tableRows,
    theme: "striped",
    headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 20, right: 20 }
  });

  const finalY = (doc as any).lastAutoTable.finalY;

  // ─── TOTALS ───
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(`TOTAL PAID (AUD):`, 120, finalY + 15);
  doc.text(`$${totalAmount.toFixed(2)}`, 190, finalY + 15, { align: "right" });

  // ─── FOOTER ───
  doc.setDrawColor(240);
  doc.line(20, 260, 190, 260);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`${data.tenantName} | ABN: ${abn}`, 105, 270, { align: "center" });
  doc.setFontSize(8);
  doc.text("No GST has been charged. Generated by TrimSpace Marketplace.", 105, 275, { align: "center" });

  return doc.output("blob");
}
