import { jsPDF } from "jspdf";
import "jspdf-autotable";

export interface InvoiceData {
  bookingId: string;
  customerName: string;
  tenantName: string;
  tenantAddress: string;
  tenantPhone: string;
  tenantABN: string;
  date: string;
  time: string;
  services: { name: string; price: number }[];
  totalPrice: number;
  status?: string;
  serviceName?: string;
  servicePrice?: number;
}

export async function generateTaxInvoice(data: InvoiceData): Promise<any> {
  const abn = data.tenantABN || "00 000 000 000";
  const priorityFee = 0.50; 
  
  // Create doc
  const doc = new jsPDF();

  // ─── BRANDING ───
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); 
  doc.setFont("helvetica", "bold");
  doc.text("TrimSpace", 20, 25);
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("PREMIUM MARKETPLACE", 20, 30);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(data.tenantName, 190, 25, { align: "right" });
  
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(data.tenantAddress || "Location Pending", 190, 31, { align: "right" });

  // ─── TITLE ───
  doc.setDrawColor(230);
  doc.line(20, 45, 190, 45);
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text("TAX INVOICE", 20, 65);

  // ─── INFO ───
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(`Invoice #: ${data.bookingId}`, 20, 80);
  doc.text(`Issued: ${new Date().toLocaleDateString("en-AU")}`, 20, 85);
  doc.text(`Visit: ${data.date} at ${data.time}`, 20, 90);

  doc.setFont("helvetica", "bold");
  doc.text("BILL TO:", 130, 80);
  doc.setFont("helvetica", "normal");
  doc.text(data.customerName, 130, 85);

  // ─── TABLE ───
  const isCancelled = data.status === "CANCELLED";
  const subtotal = (data.servicePrice || data.totalPrice || 0);
  const cancellationFee = isCancelled ? subtotal * 0.5 : 0;
  const netAmount = isCancelled ? cancellationFee : subtotal;

  const tableData = [
    [
      data.serviceName || "Booking Services", 
      `$${subtotal.toFixed(2)}`, 
      isCancelled ? "50%" : "0%", 
      `$${netAmount.toFixed(2)}`
    ]
  ];

  if (isCancelled) {
    tableData.push([
      "Cancellation Fee (50%)",
      "-",
      "-",
      `$${cancellationFee.toFixed(2)}`
    ]);
  }

  (doc as any).autoTable({
    startY: 105,
    head: [["Description", "Original Price", "Fee %", "Net Amount"]],
    body: tableData,
    theme: "striped",
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { cellWidth: 30, halign: "right" },
      2: { cellWidth: 30, halign: "center" },
      3: { cellWidth: 35, halign: "right" },
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Charged: $${netAmount.toFixed(2)}`, 190, finalY, { align: "right" });

  if (isCancelled) {
     doc.setFontSize(10);
     doc.setFont("helvetica", "italic");
     doc.setTextColor(150, 0, 0);
     doc.text("* This booking was cancelled. A 50% cancellation fee was applied.", 20, finalY + 10);
  }
  
  // Reset color for footer
  doc.setTextColor(100);

  // ─── FOOTER ───
  doc.setDrawColor(240);
  doc.line(20, 260, 190, 260);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`${data.tenantName} | ABN: ${abn}`, 105, 270, { align: "center" });
  doc.setFontSize(8);
  doc.text("No GST has been charged. Generated by TrimSpace Marketplace.", 105, 275, { align: "center" });

  return doc.output("arraybuffer");
}
